// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ZgjedhjetApi.Data;

#nullable disable

namespace ZgjedhjetApi.Migrations
{
    [DbContext(typeof(LifeDbContext))]
    partial class LifeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ZgjedhjetApi.Models.Entities.Zgjedhjet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Kategoria")
                        .HasColumnType("int");

                    b.Property<int>("Komuna")
                        .HasColumnType("int");

                    b.Property<int>("Partia")
                        .HasColumnType("int");

                    b.Property<string>("Qendra_e_Votimit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Qendra_e_Votimit");

                    b.Property<string>("VendVotimi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Vendvotimi");

                    b.Property<int>("Vota")
                        .HasColumnType("int")
                        .HasColumnName("Vota");

                    b.HasKey("Id");

                    b.ToTable("Zgjedhjet", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
